Added clickable (simple) HUD elements
joeyshuttleworth/bomberbloke pull request #15
Opened 2020-08-19 03:06 UTC by tylerkf

- Added an abstract HUD element class

- Added an abstract clickable HUD element class

- Set camera, scene and engine so that the elements are positioned correctly according to the window and input is appropriately handled

- Added a simple HUD demo on client which sets a nickname and connects the client to a local server

2020-08-19 09:33 UTC, davenewham requested changes

2020-08-19 09:33 UTC, davenewham commented on engine/hud/AbstractHudElement.hpp
> +    AbstractHudElement(int xPos, int yPos, int xDim, int yDim,
xAlignFlag and yAlignFlags could use enums such as "LEFT", "CENTERED" and "RIGHT" for better code clarity.

2020-08-19 09:33 UTC, davenewham commented on engine/hud/AbstractHudElement.hpp
> +     * xDim and yDim give the dimensions of the bounding box of the element in
Please use @param for parameters (inline with doxygen)

2020-08-21 19:04 UTC, joeyshuttleworth approved these changes
Nice work, Tyler!

2020-08-21 19:04 UTC, merged