Scene
joeyshuttleworth/bomberbloke pull request #24
Opened 2020-08-26 15:26 UTC by joeyshuttleworth

2020-08-26 22:49 UTC, tylerkf requested changes
Good work!!

2020-08-26 22:49 UTC, tylerkf commented on common/BomberBlokeScene.cpp
> +#include "BomberBlokeScene.hpp"
Capital B on bloke???

2020-08-26 22:49 UTC, tylerkf commented on engine/camera/Camera.cpp
> +        min = height;
Maybe use fmin? more readable

2020-08-26 22:49 UTC, tylerkf commented on engine/client.cpp
> +     const std::lock_guard<std::mutex> lock(_scene_mutex);
Please add a comment for this line

2020-08-26 22:49 UTC, tylerkf commented on engine/engine.cpp
> +    _pScene->draw();
Is this safe? Shouldn't we check if there is a scene first?

2020-08-26 22:49 UTC, tylerkf commented on engine/engine.hpp
>  class Camera;
Do we still need the Camera class here?

2020-08-26 22:49 UTC, tylerkf commented on engine/hud/AbstractHudElement.cpp
> +          mPosition[0] = (screenDimensions[0] - mDimensions[0]) / 2;
This is an accident

2020-08-26 22:49 UTC, tylerkf commented on engine/hud/AbstractHudElement.hpp
> +
No changes to this file should have been made

2020-08-26 22:49 UTC, tylerkf commented on engine/hud/ClickableHudElement.cpp
> +    if (event->type == SDL_MOUSEBUTTONDOWN) {
This is an accidental change

2020-08-26 22:49 UTC, tylerkf commented on common/BomberBlokeScene.hpp
> +    void LogicUpdate();
Is this mean to be camel case?

2020-08-26 22:49 UTC, tylerkf commented on engine/scene/scene.hpp
> +  virtual void LogicUpdate(){};
Camel case?

2020-08-26 22:49 UTC, tylerkf commented on engine/server.cpp
> +    const std::lock_guard<std::mutex> lock(_scene_mutex);
Please add a comment

2020-08-26 22:49 UTC, tylerkf commented on server/bomberbloke_server.cpp
> +  const std::lock_guard<std::mutex> lock(_scene_mutex);
Please add a comment

2020-08-26 22:49 UTC, tylerkf commented on common/BomberBlokeScene.cpp
> +  handle_system_command(split_to_tokens("open 127.0.0.1"));
Remove this line, in default this line is not here

2020-08-26 22:49 UTC, tylerkf commented on common/BomberBlokeScene.cpp
> +  std::cout << "clicked left button" << std::endl;
Remove this line, in default this line is not here

2020-08-26 22:49 UTC, tylerkf commented on common/BomberBlokeScene.cpp
> +  std::cout << "clicked right button" << std::endl;
Remove this line, in default this line is not here

2020-08-26 22:49 UTC, tylerkf commented on common/BomberBlokeScene.cpp
> +  handle_system_command(split_to_tokens("open 127.0.0.1"));
Remove this line, in default this line is not here

2020-08-26 22:49 UTC, tylerkf commented on common/BomberBlokeScene.cpp
> +}
Remove this, in default this is not here

2020-08-26 22:49 UTC, tylerkf commented on common/BomberBlokeScene.cpp
> +static void hudTestFn2() {
Rename this to hudTestFn1 (there shouldn't be a third one)

2020-08-26 22:49 UTC, tylerkf commented on common/BomberBlokeScene.cpp
> +static void hudTestFn3() {
Rename this to hudTestFn2 (there shouldn't be a third one)

2020-08-26 22:49 UTC, tylerkf commented on common/BomberBlokeScene.cpp
> +  onResize();
Why do we call onResize on construction? This looks like an artifact from old default code

2020-08-28 00:48 UTC, merged

2020-09-03 13:35 UTC, davenewham commented
This resolves #17